# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GSM-ARFCN
version:      0.03
version_from: lib/GSM/ARFCN.pm
installdirs:  site
requires:
    strict:                        0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
